### ISSUE TITLE
Webpack is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by oleteacher** [hlhielkema/elara#21]
Hi, nice project you have and wanting to use in a classroom student project.

Have hit an issue never experienced before. As the title says, that is is my issue:

```
xxxx@ThinkCentre MINGW64 /c/Users/Public/Documents/elara (master)
$ npm run build

> elara@1.0.0 build C:\Users\Public\Documents\elara
> webpack

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elara@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elara@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2020-09-24T19_15_08_452Z-debug.log
```

The debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle elara@1.0.0~prebuild: elara@1.0.0
6 info lifecycle elara@1.0.0~build: elara@1.0.0
7 verbose lifecycle elara@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle elara@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Public\Documents\elara\node_modules\.bin;C:\Users\xxxx\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\xxxx\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\WinSCP;C:\FPC\3.0.2\bin\i386-Win32;C:\Program Files\InstallAware\InstallAware 12;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files (x86)\Intel\Platform Flash Tool Lite;C:\Program Files\nodejs;C:\Users\xxxx\.windows-build-tools\python27;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\xxxx\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\xxxx\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\WinSCP;C:\FPC\3.0.2\bin\i386-Win32;C:\Program Files\InstallAware\InstallAware 12;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\Ruby23\bin;C:\Users\xxxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxxx\AppData\Local\Yarn\.bin;C:\Users\xxxx\AppData\Local\atom\bin;C:\Users\xxxx\AppData\Local\GitHubDesktop\bin;C:\Users\xxxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxxx\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle elara@1.0.0~build: CWD: C:\Users\Public\Documents\elara
10 silly lifecycle elara@1.0.0~build: Args: [ '/d /s /c', 'webpack' ]
11 silly lifecycle elara@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle elara@1.0.0~build: Failed to exec build script
13 verbose stack Error: elara@1.0.0 build: `webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid elara@1.0.0
15 verbose cwd C:\Users\Public\Documents\elara
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.12.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error elara@1.0.0 build: `webpack`
22 error Exit status 1
23 error Failed at the elara@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Any ideas to help me out?

Thanks!

**Comment by oleteacher** [comment]
Crazy stuff. I ran again (actually about 5 times) and it seemed to work now. Will blame this on Windows 10 :)

**Comment by hlhielkema** [comment]
@oleteacher Hi, I never encountered this problem before. Please let me know if it happens again. Thanks for letting me know anyway.
